### ISSUE TITLE
i have error when using method onAccept

### ISSUE THREAD

**Issue by devhuy57** [itisnajim/reorderable_staggered_scroll_view#1]
type '(ReorderableStaggeredScrollViewGridItem?, ReorderableStaggeredScrollViewGridItem, bool) =>void' is not a subtype of type '((ReorderableStaggeredScrollViewListItem?,ReorderableStaggeredScrollViewListItem, bool) => void)?' in type cast

**Comment by itisnajim** [comment]
list or grid? which factory u re using ?

**Comment by devhuy57** [comment]
Thank you for your reply, i am using grid.

**Comment by devhuy57** [comment]
Please tell me how to save the changed list, thank you?

**Comment by itisnajim** [comment]
you are using the latest version, it should be `0.0.1+1` instead of `0.0.1` !?


> Please tell me how to save the changed list, thank you?

you have to use a local database (like sqlite, Shared preferences or so...) to save the new items indexes when a reorder change happen (using `onDragEnd`)..

**Comment by devhuy57** [comment]
I used `onDragEnd` but still not getting the new reorder list, can you help me with an example?

**Comment by itisnajim** [comment]
> I used `onDragEnd` but still not getting the new reorder list, can you help me with an example?

sry for the late response, fixed in the version 0.0.1+2
